version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: api-web
    volumes:
      - mongo_data:/data/db
  app:
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://mongo:27017/api-web
    depends_on:
      - mongo
volumes:
  mongo_data: 